echo off
rem Set echo to only output as directed
rem
rem 
rem Last Modified: 20191025. PMBremner, DDurden

echo =======================================================================
echo:
echo    This script checks that an appropriate Python version is
echo    available for use by the tool.
echo:
echo    A message will appear alerting the User whether the
echo    search was successful, or failed.
echo:
echo    If Python for ArcMap (arcpy) is found, then the PATH is
echo    written to the file PY_PATH_autogen.txt
echo:
echo    If the search failed, then contact the tool
echo    maintainers for help, and then contact IT if the
echo    problem cannot be resolved.
echo:
echo:
echo    Last Modified by: PMBremner - pbremner@sjrwmd.com
echo                      DDurden   - Douglas.Durden@srwmd.org
echo =======================================================================
echo:


rem ---------------------------------------
rem Set the PATH to the python executable for
rem enabling support on different computers
rem EXAMPLE: set PYCOM=C:\Python27\ArcGIS10.6\python
rem ---------------------------------------

echo:
echo    Begin searching for arcpy Python. This may take a moment . . .
echo:
echo:


rem Initialize the Python PATH and check message variables to "not found"
SET PYCMD="false"
SET CKMSG="false"


rem Capture the current working directory
SET CWD=%cd%


rem Move to the root directory
cd \

rem Find arcpy and set it to an environment variable
for /F "tokens=4" %%A in ('"dir python.exe /s /p | find "ArcGIS" | find "Python27" | find /N "Python27" | findstr /r \[[1]\]"') DO (SET PYCMD=%%A\python)


rem Move back to the original working directory
cd %CWD%


rem Define the filename where the PATH to Python will be written
SET PATHFILE=PY_PATH_autogen.txt


rem If found, display the Python version
rem Otherwise throw an ERROR message
if "%PYCMD%" == "%CKMSG%" (
    echo    ERROR:  Failed to find an appropriate Python!
    echo:
    echo    Please check that you have a local installation of ArcMap 10.0 or newer
) else (
    echo    Success! The following Python was found:
    echo:
    echo    %PYCMD%
    echo:
    echo    Writing the Python PATH to file for lookup by the tool . . .
    
    
    echo -------------------------------------------------- > %PATHFILE%
    echo This file contains the local PATH to ArcGIS Python >> %PATHFILE%
    echo DO NOT EDIT THIS FILE -- IT IS AUTO-GENERATED BY: >> %PATHFILE%
    echo              check_Python_version.bat              >> %PATHFILE%
    echo -------------------------------------------------- >> %PATHFILE%
    echo %PYCMD% >> %PATHFILE%
    
    echo:
    echo    Finished writing the PATH to: %PATHFILE%
    rem echo    %PATHFILE%
    echo    This file will be used by the simulation tool when available in order to speed up Python search
    echo:
)
echo:
echo:

rem set PYCMD=C:\Python27\ArcGIS10.6\python


rem PAUSE

rem EXIT
rem =======================================
